---
## Docker Configuration
docker_install: True
docker_dev: /dev/vdb
docker_vg: dockervg
docker_data_size: 100%VG
docker_dm_basesize: "10G"
container_root_lv_name: dockerlv
container_root_lv_mount_path: /var/lib/docker
